version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: social_network
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
